# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0dfbbed2a21a78ac22a80997dc060cbfa2c00ebcfc893244b169bdb5a503f374503217cdef464166b87f5a566b740424b14f30b8eb2d24834cd496093064b878

test:
  secret_key_base: 77414b1de4b0a00dd15fd4df89bc2593b7b11cfef6636907edfc3b6ce504243bcbc0e27d926e639580b12a2833482cc17fefbd73b852c6263904a730a11d1a91

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
